// Writes src/client/brand-marks.ts: the simple-icons path of every `icon:` slug the connector
// catalogue names, so the bundle carries only the marks it shows (not the whole icon set).
//
//   npm i --no-save simple-icons && node scripts/brand-marks.mjs
//
// A slug the installed set lacks is reported and left out — the client draws a letter mark
// in the brand colour for it, so drop the `icon:` from that catalogue entry.
import { readFile, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const require = createRequire(join(root, 'package.json'))

let icons
try {
  icons = await import('simple-icons')
} catch {
  console.error('simple-icons is not installed here; run: npm i --no-save simple-icons')
  process.exit(1)
}
// the package does not export its package.json; walk up from the entry point to it
let dir = dirname(require.resolve('simple-icons'))
while (!dir.endsWith('simple-icons') && dirname(dir) !== dir) dir = dirname(dir)
const version = JSON.parse(await readFile(join(dir, 'package.json'), 'utf8')).version

const catalogue = await readFile(join(root, 'src/connectors-catalogue.ts'), 'utf8')
const slugs = [...new Set([...catalogue.matchAll(/\bicon: '([a-z0-9]+)'/g)].map((m) => m[1]))]

const bySlug = new Map()
for (const icon of Object.values(icons)) if (icon && typeof icon === 'object' && 'slug' in icon) bySlug.set(icon.slug, icon)

const lines = []
const missing = []
for (const slug of slugs) {
  const icon = bySlug.get(slug)
  if (!icon) {
    missing.push(slug)
    continue
  }
  lines.push(`  ${slug}: { d: '${icon.path}', hex: '#${icon.hex}' },`)
}

const out = `/**
 * Brand marks for the connector catalogue, the paths from simple-icons ${version}
 * (CC0 1.0), on a 24×24 viewBox. The marks and names belong to their owners
 * and only say which service a row is. Generated by scripts/brand-marks.mjs —
 * run it again when the catalogue gains a service. Entries the set lacks get a
 * letter mark in the brand colour instead.
 */
export const MARKS: Record<string, { d: string; hex: string }> = {
${lines.join('\n')}
}
`
await writeFile(join(root, 'src/client/brand-marks.ts'), out)
console.log(`${lines.length} marks written from simple-icons ${version}`)
if (missing.length) console.error(`not in simple-icons (drop the icon: from these entries): ${missing.join(', ')}`)
